# Site settings
title: "matt_villarreal's blog"
email: vmatthew360@gmail.com
description: "A dark blog theme for Jekyll."
baseurl: ""
url: "https://mvillarreal88.github.io/"
title_description: "My name is Matthew Villarreal, and I am a Data Analyst with a background in the insurance industry with skills in Excel, Pandas, Python, and SQL. I received my bachelor’s degree from St. Mary’s university in Business Administration as well as more recently my Certificate from the University of Texas San Antonio Data Analytics Bootcamp. I possess an intellectual interest in visualizing and cleaning large datasets, including unclean data sets whether they be structured or not. With a desire to grow my understanding of how to leverage data for business insights and leadership skills. My goal is to use my blog posts to continue my understanding of Data and professional development."
title_image: "https://drive.google.com/uc?id=1nbCVKcaUuBScbV4pzOtjspUcRgx_Vr-d"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/Mvillarreal88
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username:  Mvillarreal88
instagram_username: 
reddit_username: 
linkedin_link: https://www.linkedin.com/in/matthew-villarreal-1060a/
google_plus_link: 
stackoverflow_link: https://stackoverflow.com/users/15524268/matthew-villarreal
xing_link:
facebook_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
